/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public String getAddMessage(int a, int b) {
    int sum = new Calculate().sum(a, b);
    float ave = (float) sum / 2;
    return "Sum of " + a + " and " + b + " is " + sum + ". Average is " + ave + ".";
  }

  public String getAtoBMessage(int a, int b) {
    for (int i=a, i <= b; i++){
      sum 
    }
    int sum = new Calculate().sum(a, b);
    float ave = (float) sum / 2;
    return "Sum of " + a + " to " + b + " is " + sum + ". Average is " + ave + ".";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    System.out.println(new App().getAddMessage(2, 3));
    System.out.println(new App().getAtoBMessage(10, 55));
  }
}
