/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  // public String getCalcMessage() {
  // return
  // }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    int a = 2, b = 3;
    sum = new Calculate().sum(a, b);
    System.out.println("Sum of " + a + "and" + b + " is " + sum + ". Average is ");
  }
}
