/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public String getCalcMessage(int a, int b) {
    int sum = new Calculate().sum(a, b);
    float ave = sum / 2;
    return "Sum of " + a + " and " + b + " is " + sum + ". Average is " + ave + ".";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    System.out.println(new App().getCalcMessage(2, 3));
    System.out.println(new App().getCalcMessage(10, 55));
  }
}
